### ISSUE TITLE
Request for enhancements

### ISSUE THREAD

**Issue by Taakn** [thatsmydoing/cloudflare-webui#1]
Hi,

First of all I wanted to thank you for making this. This is exactly what I've been looking for given the absence of functionality in the Partner Portal... And I didn't want to deal with cPanel. I think you could try and push it to CF as a recommended UI.

I had some questions / requests for enhancements: 
- Would it be possible to have an option to disable the whitelist (or if the array is empty, just list everything)?
- Would it be possible to show in the settings (as readonly) the name servers for the domain name?
- Finally, would it be possible to add domaine names with the full_zone_set API? For instance: 
  `https://api.cloudflare.com/host-gw.html?host_key=XXX&user_key=YYY&act=full_zone_set&zone_name=ZZZ`

I could try to do a PR if you'd prefer at some point. 

Thanks again

**Comment by thatsmydoing** [comment]
Hi! I'm glad you find it useful. The first 2 I can do, but the last one is only for CloudFlare partners, which I don't have access to.

**Comment by Taakn** [comment]
Thanks a lot for #1 and #2. Yes the partner portal is basically completely empty, you can't add a domain name, or modify zones. So this tool is quite fantastic! I found it through a reddit post you had made. Your does app deserve to be better known among CF partners.

**Comment by Taakn** [comment]
Ha also don't know if it's possible, but would it be possible to make MX records writeable ? 

Thanks again!

**Comment by thatsmydoing** [comment]
I didn't make it writeable since the input was more complicated than just a text box. I'll have to look into it a bit.
