### ISSUE TITLE
Error of  Option::unwrap() 

### ISSUE THREAD

**Issue by mrbupu** [thatsmydoing/cloudflare-webui#2]
Hi there,

I ran the latest release. but it doesn't work.
Can you tell me how to fix it.
 ./cloudflare-webui
Loading configuration from ./config.json
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:     0x7f09ebc39729 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x7f09ebc3dc8c - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x7f09ebc3cb59 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x7f09ebc3d248 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x7f09ebc3d0a2 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x7f09ebc3d010 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x7f09ebc3cf91 - rust_begin_unwind
   8:     0x7f09ebc77cbf - core::panicking::panic_fmt::hbfc935564d134c1b
   9:     0x7f09ebc77beb - core::panicking::panic::hcee64434f097e399
  10:     0x7f09ebaaa188 - cloudflare_webui::actual_main::hfd114beb7a1fefb5
  11:     0x7f09ebaac465 - cloudflare_webui::main::h423763568bb76c5a
  12:     0x7f09ebc45776 - __rust_maybe_catch_panic
  13:     0x7f09ebc3c2d2 - std::rt::lang_start::h53bf99b0829cc03c
  14:     0x7f09eb6470b2 - __libc_start_main
  15:     0x7f09eba88f28 - <unknown>
  16:                0x0 - <unknown>

**Comment by mrbupu** [comment]
Hi 

Thank for your reply . My config.json is beloved.
I set whitelist null to disable whitelist feature. But it still has the same error

{
    "port": 8080,
    "email": "xxx@gmail.com",
    "token": "xxx",
    "whitelist": [
        ""
    ]
}

**Comment by thatsmydoing** [comment]
Ah, by setting it to null, I mean
```
{
    "port": 8080,
    "email": "xxx@gmail.com",
    "token": "xxx",
    "whitelist": null
}
```

**Comment by mrbupu** [comment]
Hi 

Thank you for your reply.
I started it. but ca get any infomation of domain. 
I think cloudflare api endpoint is changed. Can you tell me how to start it from source code. and how to build it to executable file.

I will try to fix it.

**Comment by thatsmydoing** [comment]
Trying it locally, it still works for me. You have to use an API Key instead of an API token though. I think that's new and the terminology got conflated.

**Comment by thatsmydoing** [comment]
> Can you tell me how to start it from source code. and how to build it to executable file.

There's 2 versions of the server. The node server still starts with just `npm install` and `npm start`. The rust server has a makefile that should build it but I couldn't get it to build on my machine anymore. I don't know if you'll have better luck.

I also made a branch that uses API tokens instead here https://github.com/thatsmydoing/cloudflare-webui/tree/api-token but I won't be developing this any more.

Cloudflare already supports multi-user accounts so the only reason you'd want to keep using this is the whitelist functionality. I'll be archiving the repository so if you want to keep working on it, feel free to fork.
